config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :children, class_name: "Comment", foreign_key: "parent_id"
  scope :roots, -> { where(parent_id: nil) }
end

app/models/subcomment.rb
class Subcomment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def nested_comments(comments)
  #   comments.map do |comment, sub_comments|
  #     render(comment) + content_tag(:div, nested_comments(sub_comments), class: "nested_comments")
  #   end.join.html_safe
  # end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    if params[:id] 
      @parent = Comment.find(params[:id]) 
    else
      @parent = nil
    end
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(title: params[:comment][:title],
                     content: params[:comment][:content],
                     user_id: params[:comment][:user_id],
                     parent_id: params[:comment][:parent_id])

      if @comment.save
        return redirect_to comment_path(@comment)
      end
    render :new
  end


  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path, notice: "Comment was successfully erased."
  end
  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # def nested_comments(comments)
  #   comments.map do |comment, sub_comments|
  #     render(comment) + content_tag(:div, nested_comments(sub_comments), class: "nested_comments")
  #   end.join.html_safe
  # end

  def index
    # @comments = Comment.all
    @comments = Comment.roots
    # tmp_com = Comment.all
    # tmp_com.each do |each_com|
    #   if each_com.parent_id.nil?
    #     allcom << each_com
    #     lastparent = each_com
    #   else
    #     tmp_com.each do |new_com|
    #       if new_com.parent_id == lastparent.id
    #         allcom << new_com


  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
# module HomeHelper
#   def render_comments(comments, depth = 0)
#     comments.map do |comment|
#       content_tag(:div, class: "comment", style: "padding-left: #{depth * 20}px;") do
#         content_tag(:p, comment.content) +
#         (render_comments(comment.children, depth + 1) if comment.children.any?).to_s
#       end
#     end.join.html_safe
#   end
# end

# module HomeHelper
#   def render_comments(comments, depth = 0)
#     comments.map do |comment|
#       content_tag(:div, class: "comment", style: "padding-left: #{depth * 20}px;") do
#         content_tag(:p, comment.content) +
#         content_tag(:div, render_comments(comment.children, depth + 1), class: "children") if comment.children.any?
#       end
#     end.join.html_safe
#   end
# end

# module HomeHelper
#   def render_comments(comments, depth = 0)
#     comments.map do |comment|
#       content_tag(:div, class: "comment", style: "padding-left: #{depth * 20}px;") do
#         content_tag(:p, comment.content) +
#         content_tag(:div, class: "children") do
#           (render_comments(comment.children, depth + 1) if comment.children.any?).to_s
#         end
#       end
#     end.join.html_safe
#   end
# end

module HomeHelper
  def render_comments(comments, depth = 0)
    comments.map do |comment|
      content_tag(:div, class: "comment", style: "padding-left: #{depth * 20}px;") do
        content_tag(:div, class:"title") do
        link_to(comment.title, comment_path(comment)) 
        end +
        content_tag(:div, class: "user") do
          comment.user.name
        end +
        content_tag(:div, class: "created_at") do
          comment.created_at
        end +
        content_tag(:div, class: "content") do
          comment.content
        end +
        content_tag(:br) +
        content_tag(:div, class: "children") do
          (render_comments(comment.children, depth + 1) if comment.children.any?).to_s
        end
      end
    end.join.html_safe
  end
end

app/views/comments/new.html.erb
<%= form_with model: @comment do |c| %>
  <dl>
    <dt>
      <%= c.label 'Título'%>
      <%= c.text_field :title %>
    </dt>
    <dt>
      <%= c.label 'Texto'%>
      <%= c.text_area :content, rows: 15, cols: 50 %>
    </dt>
    <dt>
      <%= c.collection_select :user_id, User.all, :id, :name %>
      <% if @parent %>
        Parent: <%= @parent.id %>
        <%= c.hidden_field :parent_id, value: @parent.id %>
      <% end %>
    </dt>
    <dt>
      <%= c.submit 'Salvar' %>
    </dt>
  </dl>
<% end %>

app/views/comments/show.html.erb
<h1>Post: <%= @comment.title %> </h1>

<dl>
    <dt>
      <strong>Texto: </strong><%= @comment.content %>
    </dt>
    <dt>
      <strong>Criado em: </strong><%= @comment.created_at %>
    </dt>
    <dt>
      <strong>Por: </strong><%= @comment.user.name %>
    </dt>
    <dt> 
      <%= link_to "novo comentário", new_comment_path(id: @comment.id) %>
    </dt>
    <dt>
      <%= button_to "Erase Comment", comment_path(@comment), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
    </dt>
</dl>

app/views/home/index.html.erb
<%= render_comments(@comments) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="menu">
      <div class="item">
        <%= link_to "Home", root_path %>
      </div>
      <div class="item">
        <%= link_to "Novo comentário", new_comment_path %>
      </div>
      <div class="item">
        <%= link_to "Novo usuário", new_user_path %>
      </div>
    </div>
    <br />
    <br />
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>
</div>